---
- name: Check which htop version if available
  ansible.builtin.include_tasks:
    file: compile/version.yml

- name: Install compiled htop
  ansible.builtin.include_tasks:
    file: compile/install.yml
  when: (not ansible_check_mode and (htop_active_version.stdout != htop__version_target))
