---
- name: check htop version if available
  ansible.builtin.include_tasks: compile/version.yml

- name: compile htop
  ansible.builtin.include_tasks: compile/install.yml
  when: (not ansible_check_mode and (htop_active_version.stdout != htop__version_target))
