---
- name: Check which htop version if available
  ansible.builtin.include_tasks:
    file: compile/version.yml

- name: Load OS specific variables
  ansible.builtin.include_vars:
    file: "{{ lookup('first_found', htop__load_vars) }}"

- name: Install compiled htop
  ansible.builtin.include_tasks:
    file: compile/install.yml
  when: (not ansible_check_mode and (htop_active_version.stdout != htop__version_target))
