---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install htop via package manager
  ansible.builtin.include_tasks: install.yml
  when: htop__compile | bool

- name: compile htop from source
  ansible.builtin.include_tasks: compile.yml
  when: not htop__compile | bool
