---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install htop via package manager
  ansible.builtin.include_tasks:
    file: 'install.yml'
  when: not htop__compile | bool

- name: Compile htop from source
  ansible.builtin.include_tasks:
    file: 'compile.yml'
  when: htop__compile | bool
