---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when: ansible_pkg_mgr == "apt"

- name: Install build requirements
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  loop: "{{ htop__compile_requirements }}"

- name: Create directory to compile htop
  ansible.builtin.tempfile:
    state: 'directory'
    suffix: htop
  register: htop__compile_dir

- name: Checkout desired htop version
  ansible.builtin.git:
    dest: "{{ htop__compile_dir.path }}/htop_git"
    version: "{{ htop__version_target }}"
    repo: 'https://github.com/htop-dev/htop.git'
  register: htop__compile_repo

- name: Run autogen.sh
  ansible.builtin.command:
    cmd: './autogen.sh'
  args:
    chdir: "{{ htop__compile_dir.path }}/htop_git"
  changed_when: "htop__compile_dir.changed | bool or htop__compile_repo.changed | bool"

- name: Run configure
  ansible.builtin.command:
    cmd: "./configure --prefix={{ htop__compiled_path_prefix }}"
  args:
    chdir: "{{ htop__compile_dir.path }}/htop_git"
  changed_when: "htop__compile_dir.changed | bool or htop__compile_repo.changed | bool"

- name: Build the default target
  community.general.make:
    chdir: "{{ htop__compile_dir.path }}/htop_git"
  changed_when: "htop__compile_dir.changed | bool or htop__compile_repo.changed | bool"

- name: "Install htop to {{ htop__compiled_path_prefix }}"
  become: true
  community.general.make:
    chdir: "{{ htop__compile_dir.path }}/htop_git"
    target: 'install'
  changed_when: "htop__compile_dir.changed | bool or htop__compile_repo.changed | bool"
